version: "3.8"

services:
  api:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lightwork
      - PORT=3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npx prisma migrate deploy && npx prisma generate && npm run start"

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lightwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
